
package com.sparta.jukebox;


import java.awt.event.*;
import javax.swing.*;
import java.util.*; 

/**
 *
 * @author frednyakagwa
 */
public class CreatePlaylist extends javax.swing.JFrame {

    /**
     * Creates new form CreatePlaylist
     */
    
    
    public CreatePlaylist() {
        //System.out.println("Loaded");
        //allTracksTextArea.setText("Loading");
        initComponents();
        allTracksTextArea.setText(LibraryData.listAll());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        playlistTxtArea = new java.awt.TextArea();
        jLabel2 = new javax.swing.JLabel();
        trackNoTxtFld = new java.awt.TextField();
        allTracksTextArea = new java.awt.TextArea();
        clearPlaylistBtn = new javax.swing.JButton();
        checkTrackBtn = new javax.swing.JButton();
        addTrackToPlaylist = new javax.swing.JButton();
        removeSelectedTrackBtn = new javax.swing.JButton();
        exitPlaylistBtn = new javax.swing.JButton();
        selectedTrackTxtArea = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Enter Track Number :");

        jLabel2.setText("All Tracks");

        trackNoTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trackNoTxtFldActionPerformed(evt);
            }
        });

        allTracksTextArea.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                allTracksTextAreaComponentShown(evt);
            }
        });

        clearPlaylistBtn.setText("Clear Playlist");
        clearPlaylistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPlaylistBtnActionPerformed(evt);
            }
        });

        checkTrackBtn.setText("Check track");
        checkTrackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTrackBtnActionPerformed(evt);
            }
        });

        addTrackToPlaylist.setText("Add Track to Playlist");
        addTrackToPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrackToPlaylistActionPerformed(evt);
            }
        });

        removeSelectedTrackBtn.setText("Remove Track");

        exitPlaylistBtn.setText("Exit");
        exitPlaylistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitPlaylistBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(selectedTrackTxtArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(exitPlaylistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(playlistTxtArea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(136, 136, 136)
                                        .addComponent(trackNoTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(checkTrackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(allTracksTextArea, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(addTrackToPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(removeSelectedTrackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(clearPlaylistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(allTracksTextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkTrackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(trackNoTxtFld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectedTrackTxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTrackToPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeSelectedTrackBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearPlaylistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(playlistTxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(exitPlaylistBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trackNoTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trackNoTxtFldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trackNoTxtFldActionPerformed

    private void exitPlaylistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitPlaylistBtnActionPerformed
        // TODO add your handling code here:
           dispose();
    }//GEN-LAST:event_exitPlaylistBtnActionPerformed

    private void checkTrackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTrackBtnActionPerformed
        // TODO add your handling code here:
            String selectedTrackNumber = trackNoTxtFld.getText();
            
            String name = LibraryData.getName(selectedTrackNumber);
            //System.out.println(name);
            if (name == null) {
                //information.setText(" No such track number");
                selectedTrackTxtArea.setText("No such track number");
            } else {
                selectedTrackTxtArea.setText(name + " - " + LibraryData.getArtist(selectedTrackNumber));
                selectedTrackTxtArea.append("\nRating: " + displayStars(LibraryData.getRating(selectedTrackNumber)));
                selectedTrackTxtArea.append("\nPlay count: " + LibraryData.getPlayCount(selectedTrackNumber));
            }
      
    }//GEN-LAST:event_checkTrackBtnActionPerformed

    private void addTrackToPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrackToPlaylistActionPerformed
        // TODO add your handling code here:
        String selectedTrackNumber = trackNoTxtFld.getText();
            
            String name = LibraryData.getName(selectedTrackNumber);
            //System.out.println(name);
            if (name == null) {
                //information.setText(" No such track number");
                selectedTrackTxtArea.setText("No such track number");
            } else {
            
                playlistTxtArea.append(name + " - " + LibraryData.getArtist(selectedTrackNumber));
                playlistTxtArea.append("\nRating: " + displayStars(LibraryData.getRating(selectedTrackNumber)));
                playlistTxtArea.append("\nPlay count: " + LibraryData.getPlayCount(selectedTrackNumber));
                playlistTxtArea.append("\n - - - - - - - - -- - - - - - - - - - - - - - - - - - - - - - - - -  \n");
            }
    }//GEN-LAST:event_addTrackToPlaylistActionPerformed

    private void allTracksTextAreaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_allTracksTextAreaComponentShown
        // TODO add your handling code here:
        //allTracksTextArea.setText("No tracks");
    }//GEN-LAST:event_allTracksTextAreaComponentShown

    private void clearPlaylistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPlaylistBtnActionPerformed
        // TODO add your handling code here:
        playlistTxtArea.setText("");
        
    }//GEN-LAST:event_clearPlaylistBtnActionPerformed

    private String displayStars(int rating) {
          String stars = "";
          for (int i = 0; i < rating; ++i) {
              stars += "*";
          }
          return stars;
      }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTrackToPlaylist;
    private java.awt.TextArea allTracksTextArea;
    private javax.swing.JButton checkTrackBtn;
    private javax.swing.JButton clearPlaylistBtn;
    private javax.swing.JButton exitPlaylistBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.TextArea playlistTxtArea;
    private javax.swing.JButton removeSelectedTrackBtn;
    private java.awt.TextArea selectedTrackTxtArea;
    private java.awt.TextField trackNoTxtFld;
    // End of variables declaration//GEN-END:variables
}
